export const headerMappings: { [key: string]: string[] } = {
  slNo: ["SL NO"],
  name: ["NAME"],
  scheme: ["SCHEME"],
  loanNo: ["LOAN NO", "LOAN NEW"],
  agreementNumber: ["agreement number"],
  requiredAmount: ["REQUIRED Amount"],
  amountSanctioned: ["AMOUNT SANCTIONED"],
  installment1: ["INSTALLMENT 1"],
  installment2: ["INSTALLMENT 2"],
  installment3: ["INSTALLMENT 3"],
  installment4: ["INSTALLMENT 4"],
  legalFeeAmount: ["LEGAL FEE"],
  processingFeeAmount: ["PROCESSING FEE"],
  bcAmount: ["BC"],
  bankAccountNo: ["ACCOUNT NO", "ACCOUNT NUMBER"],
  bankIfsc: ["IFSC"],
  bankName: ["BANK NAME", "NAME"],
  bankBranch: ["BRANCH"],
};